export const USAGE_VERSION = "2026-10-04.2";
export interface UsageAcceptance {
  version: string;
  accepted_at: number;
  terms_version?: string;
}
export const usageNotice = `<section class="notice" id="data-notice" aria-labelledby="notice-title"><h2 id="notice-title">Know what you’re connecting</h2><p class="notice-intro">Learning MCP is an independent service, not affiliated with your institution or platform providers. Read this before connecting an account or authorizing a client.</p><div class="notice-grid"><section><h3>Where your data goes</h3><p>Requests, credentials and browser sign-in are processed by this service and the infrastructure providers used by its operator, including Cloudflare. Course content, discussions, feedback and task information you request are sent to the MCP client you authorize and are subject to that client’s data handling.</p></section><section><h3>What is stored</h3><p>Ed API tokens are processed in the suite. SSO and Moodle / OnTrack credentials are processed in the private sign-in broker. Platform tokens and browser sessions are stored encrypted. Saving your encrypted password is optional. Saving a TOTP secret requires a separate, additional choice. Without those choices, your password and TOTP setup key are used for the current sign-in only; encrypted sessions may still be saved and renewed. A TOTP secret can generate future MFA codes. The operator can access encrypted credentials using its keys. Secrets are never returned through MCP or administration. One-time codes are never saved.</p></section><section><h3>Your permissions and responsibilities</h3><p>You need permission to automate access to your accounts and send the requested material to your client. Check your institution’s and platforms’ rules, copyright and privacy requirements, and each assessment’s AI instructions. Only use attendance codes for classes you actually attended. This service never submits attendance or changes learning progress.</p></section><section><h3>You can remove access</h3><p>Remove your saved sign-in while keeping platform sessions and their renewal cookies. Disconnecting a platform deletes its session and renewal material; disconnecting both Moodle and OnTrack also removes the shared saved sign-in. You can revoke client access here. Signing out of this page leaves your platform connections in place.</p></section></div><p class="notice-note">Acknowledging this notice records that you have read it. It does not grant rights, establish institutional approval or certify compliance.</p></section>`;
export const usageLabel =
  "I have read the privacy and credential notice, including how data is sent to my authorized client.";

export const termsApproval = `<label class="check"><input type="checkbox" name="terms_consent" value="accept" required><span>I agree to the <a href="/terms" target="_blank" rel="noopener">Terms of use</a> and confirm that I have the permissions required for my use.</span></label>`;
